"""
dossier_generator.py — T2: Full repurposing dossier (Markdown → PDF).

Assembles all T2 outputs into a structured repurposing dossier:
  - Executive summary
  - Drug profile
  - Indication overview
  - Evidence synthesis
  - Dose rationale
  - Biomarkers / patient stratification
  - Phase II trial design
  - Competitive landscape
  - Risk assessment and confidence rating

Output: Markdown file + optional PDF via weasyprint or reportlab.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

DOSSIER_TEMPLATE = """# Repurposing Dossier: {drug_name} for {indication_name}

**Generated:** {date}
**Overall Confidence:** {confidence:.0%}
**Composite Score:** {composite_score:.3f}

---

## Executive Summary

{evidence_summary}

---

## Drug Profile

| Field | Value |
|-------|-------|
| Drug Name | {drug_name} |
| Generic Name | {generic_name} |
| Drug Type | {drug_type} |
| Approval Status | {status} |
| Primary Targets | {primary_targets} |
| Mechanism | {mechanism} |
| Half-life | {half_life} |

### Black Box Warnings
{black_box_warnings}

---

## Indication Overview

| Field | Value |
|-------|-------|
| Indication | {indication_name} |
| MeSH ID | {mesh_id} |
| ICD-10 | {icd10} |
| Prevalence | {prevalence} |
| Orphan Status | {orphan_status} |

### Disease Genes (Top 10)
{disease_genes}

---

## Evidence Synthesis

{evidence_synthesis}

### Evidence Breakdown
{evidence_breakdown}

---

## Dose Rationale

{dose_rationale}

---

## Patient Stratification Biomarkers

{biomarkers}

---

## Phase II Trial Design

{trial_design}

---

## Competitive Landscape

{competitive_landscape}

---

## Risk Assessment

{risk_assessment}

---

## References

{references}

---

*Generated by clinical-trial-repurposing-pipeline-core*
"""


def generate_dossier(
    drug: dict,
    indication: dict,
    evidence_summary: str,
    trial_design: dict,
    config,  # PipelineConfig
    run: dict | None = None,
) -> Path:
    """
    Generate a Markdown repurposing dossier for a T2 candidate.

    Returns the path to the generated Markdown file.
    """
    from datetime import date

    drug_name = drug.get("name") or drug.get("drug_id")
    indication_name = indication.get("name") or indication.get("indication_id")
    slug = f"{drug.get('drug_id', 'drug')}_{indication.get('indication_id', 'indication')}"

    results_dir = Path(config.output.results_dir) / "dossiers"
    results_dir.mkdir(parents=True, exist_ok=True)

    # Format primary targets
    primary_targets = _format_targets(drug.get("primary_targets"))
    bbw = _format_list(drug.get("black_box_warnings"), "No black box warnings")
    disease_genes = _format_gene_list(indication.get("disease_genes"))

    # Format trial design
    trial_design_md = _json_to_markdown_table(trial_design) if trial_design else "No trial design generated."

    # Scores
    confidence = (run or {}).get("t2_confidence") or 0.0
    composite_score = (run or {}).get("composite_score") or 0.0

    # Biomarkers
    biomarkers_raw = (run or {}).get("t2_biomarkers") or []
    if isinstance(biomarkers_raw, str):
        try:
            biomarkers_raw = json.loads(biomarkers_raw)
        except Exception:
            biomarkers_raw = []
    biomarkers_md = _format_biomarkers(biomarkers_raw)

    # Competitive landscape
    landscape_raw = (run or {}).get("t2_competitive_landscape") or {}
    if isinstance(landscape_raw, str):
        try:
            landscape_raw = json.loads(landscape_raw)
        except Exception:
            landscape_raw = {}
    landscape_md = _format_landscape(landscape_raw)

    # Dose rationale
    dose_raw = (run or {}).get("t2_dose_rationale") or {}
    if isinstance(dose_raw, str):
        try:
            dose_raw = json.loads(dose_raw)
        except Exception:
            dose_raw = {"note": str(dose_raw)}
    dose_md = _json_to_markdown_table(dose_raw) if dose_raw else "No dose analysis generated."

    content = DOSSIER_TEMPLATE.format(
        drug_name=drug_name,
        indication_name=indication_name,
        date=str(date.today()),
        confidence=confidence,
        composite_score=composite_score,
        evidence_summary=evidence_summary or "Evidence synthesis not available.",
        generic_name=drug.get("generic_name") or "—",
        drug_type=drug.get("drug_type") or "—",
        status=drug.get("status") or "—",
        primary_targets=primary_targets,
        mechanism=(drug.get("mechanism_of_action") or "Unknown")[:500],
        half_life=drug.get("half_life") or "—",
        black_box_warnings=bbw,
        mesh_id=indication.get("mesh_id") or "—",
        icd10=indication.get("icd10_code") or "—",
        prevalence=f"{indication.get('prevalence', 0):,.0f} patients" if indication.get("prevalence") else "—",
        orphan_status="Yes" if indication.get("orphan_status") else "No",
        disease_genes=disease_genes,
        evidence_synthesis=evidence_summary or "See evidence table.",
        evidence_breakdown="See evidence table in results/ directory.",
        dose_rationale=dose_md,
        biomarkers=biomarkers_md,
        trial_design=trial_design_md,
        competitive_landscape=landscape_md,
        risk_assessment=_format_risk(run or {}, drug),
        references="Evidence items stored in database evidence table.",
    )

    md_path = results_dir / f"{slug}_dossier.md"
    md_path.write_text(content)
    log.info(f"Dossier written: {md_path}")

    # Optional PDF
    if config.output.export_dossiers:
        _try_export_pdf(md_path)

    return md_path


def _try_export_pdf(md_path: Path) -> None:
    """Try to convert Markdown → PDF via weasyprint (optional dependency)."""
    try:
        import markdown
        import weasyprint

        html_content = markdown.markdown(md_path.read_text(), extensions=["tables"])
        pdf_path = md_path.with_suffix(".pdf")
        weasyprint.HTML(string=html_content).write_pdf(str(pdf_path))
        log.info(f"PDF written: {pdf_path}")
    except ImportError:
        log.debug("weasyprint/markdown not installed — PDF export skipped")
    except Exception as e:
        log.warning(f"PDF export failed: {e}")


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _format_targets(targets) -> str:
    if not targets:
        return "Unknown"
    if isinstance(targets, str):
        try:
            targets = json.loads(targets)
        except Exception:
            return targets
    if isinstance(targets, list):
        return ", ".join(
            t.get("gene_name") or t.get("uniprot_id") or str(t)
            for t in targets[:5] if isinstance(t, dict)
        )
    return str(targets)


def _format_list(field, default: str = "None") -> str:
    if not field:
        return default
    if isinstance(field, str):
        try:
            field = json.loads(field)
        except Exception:
            return f"- {field}"
    if isinstance(field, list):
        return "\n".join(f"- {item}" for item in field) or default
    return str(field)


def _format_gene_list(disease_genes) -> str:
    if not disease_genes:
        return "No disease genes loaded."
    if isinstance(disease_genes, str):
        try:
            disease_genes = json.loads(disease_genes)
        except Exception:
            return disease_genes
    if isinstance(disease_genes, list):
        genes = []
        for g in disease_genes[:10]:
            if isinstance(g, dict):
                sym = g.get("gene_symbol") or g.get("gene_name") or "?"
                score = g.get("score")
                genes.append(f"- {sym}" + (f" (score: {score:.2f})" if score else ""))
            elif isinstance(g, str):
                genes.append(f"- {g}")
        return "\n".join(genes)
    return str(disease_genes)


def _format_biomarkers(biomarkers: list) -> str:
    if not biomarkers:
        return "No biomarkers identified."
    lines = []
    for b in biomarkers:
        if isinstance(b, dict):
            lines.append(
                f"**{b.get('biomarker', '?')}** ({b.get('type', '?')}): "
                f"{b.get('rationale', '')} "
                f"Measurement: {b.get('measurement', '?')}"
            )
    return "\n\n".join(lines) if lines else "No biomarkers identified."


def _format_landscape(landscape: dict) -> str:
    if not landscape:
        return "Competitive landscape not analyzed."
    lines = [
        f"**Overall Assessment:** {landscape.get('overall_competitive_assessment', '—')}",
        f"**Differentiation:** {landscape.get('differentiation_strategy', '—')}",
        f"**Freedom to Operate:** {landscape.get('freedom_to_operate', '—')}",
    ]
    competing = landscape.get("competing_drugs", [])
    if competing:
        lines.append("\n### Competing Programs")
        for c in competing[:5]:
            lines.append(
                f"- **{c.get('drug')}** ({c.get('phase')}): {c.get('mechanism')} — {c.get('sponsor')}"
            )
    return "\n".join(lines)


def _format_risk(run: dict, drug: dict) -> str:
    safety_score = run.get("t1_safety_score") or 0.0
    evidence_score = run.get("t1_evidence_score") or 0.0
    risk_level = "Low" if safety_score > 0.7 else ("Moderate" if safety_score > 0.4 else "High")
    return (
        f"**Safety Risk:** {risk_level} (safety score: {safety_score:.2f})\n\n"
        f"**Evidence Maturity:** {evidence_score:.2f} (0=none, 1=strong clinical)\n\n"
        f"**Key Risk Factors:** See adverse event profile in database."
    )


def _json_to_markdown_table(data: dict) -> str:
    """Convert a flat dict to a two-column Markdown table."""
    if not data:
        return "—"
    rows = ["| Field | Value |", "|-------|-------|"]
    for k, v in data.items():
        val = json.dumps(v) if isinstance(v, (list, dict)) else str(v)
        rows.append(f"| {k} | {val[:200]} |")
    return "\n".join(rows)
